name: Release Pipeline

on:
  push:
    branches:
      - main

jobs:
  create-release:
    name: Crear rama release y mezclar con master
    runs-on: ubuntu-latest
    if: ${{ contains(github.event.head_commit.message, 'release') }}
    
    steps:
    - name: Checkout del repositorio
      uses: actions/checkout@v3

    - name: Setup Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: Crear rama release desde main
      run: |
        git checkout main
        git pull origin main
        git checkout -b release
        git push -u origin release

    - name: Mezclar main -> release
      run: |
        git checkout release
        git merge main
        git push origin release
